### ISSUE TITLE
Networking Optimization

### ISSUE THREAD

**Issue by gr81ape** [filip3311/filipdylanryan#1]
So networking's finally up and alive! However, it's a little slow and, while completely fine for the project, could use a little bit of speed-up for playability. Right now it takes about 5 seconds to start a new round as soon as the current player takes their last turn, with two 1-second Thread.sleep commands to ensure a lack of race conditions in changing global condition checks isSynced (for the central map) and playerFinished (for other player end conditions). Anything that can speed this up would be excellent, but is a low priority!

**Comment by gr81ape** [comment]
I removed a Thread.sleep(3000) command after the player's done their turn; this was originally in place so the player could see that their round had finished (in a single-player game), but with the anti-race delays in place there is just the right amount of time between turns in single-player mode. Problem solved!

**Comment by filiptodoric** [comment]
Nice, definitely will help with playability.
